import { normalizeInlineText } from "./dictionary-utils";

type LemmaRule = {
  suffix: string;
  lemmas: (stem: string) => string[];
  minStemLength?: number;
};

const IRREGULAR_FORMS: Record<string, string[]> = {
  caibo: ["caber"],
  coube: ["caber"],
  couber: ["caber"],
  coubera: ["caber"],
  couberam: ["caber"],
  couberem: ["caber"],
  couberia: ["caber"],
  couberiam: ["caber"],
  da: ["dar"],
  dais: ["dar"],
  damos: ["dar"],
  dara: ["dar"],
  darao: ["dar"],
  darei: ["dar"],
  darem: ["dar"],
  daria: ["dar"],
  dariam: ["dar"],
  davam: ["dar"],
  dava: ["dar"],
  dei: ["dar"],
  demos: ["dar"],
  deu: ["dar"],
  deram: ["dar"],
  der: ["dar"],
  dera: ["dar"],
  derem: ["dar"],
  desse: ["dar"],
  dessem: ["dar"],
  digo: ["dizer"],
  diz: ["dizer"],
  dizem: ["dizer"],
  dizes: ["dizer"],
  direi: ["dizer"],
  dira: ["dizer"],
  dirao: ["dizer"],
  diria: ["dizer"],
  diriam: ["dizer"],
  disse: ["dizer"],
  disseram: ["dizer"],
  disser: ["dizer"],
  dissera: ["dizer"],
  disserem: ["dizer"],
  dissesse: ["dizer"],
  dissessem: ["dizer"],
  dizia: ["dizer"],
  diziam: ["dizer"],
  e: ["ser"],
  era: ["ser"],
  eram: ["ser"],
  eras: ["ser"],
  es: ["ser"],
  esta: ["estar"],
  estais: ["estar"],
  estao: ["estar"],
  estar: ["estar"],
  estara: ["estar"],
  estarao: ["estar"],
  estarei: ["estar"],
  estaria: ["estar"],
  estariam: ["estar"],
  estamos: ["estar"],
  estando: ["estar"],
  estejam: ["estar"],
  esteja: ["estar"],
  estejamos: ["estar"],
  esteve: ["estar"],
  estiveram: ["estar"],
  estiver: ["estar"],
  estivera: ["estar"],
  estiverem: ["estar"],
  estivesse: ["estar"],
  estivessem: ["estar"],
  estive: ["estar"],
  estivemos: ["estar"],
  estava: ["estar"],
  estavam: ["estar"],
  estou: ["estar"],
  faz: ["fazer"],
  fazeis: ["fazer"],
  fazem: ["fazer"],
  fazemos: ["fazer"],
  fazes: ["fazer"],
  fara: ["fazer"],
  farao: ["fazer"],
  farei: ["fazer"],
  faria: ["fazer"],
  fariam: ["fazer"],
  fez: ["fazer"],
  fizer: ["fazer"],
  fizera: ["fazer"],
  fizeram: ["fazer"],
  fizerem: ["fazer"],
  fizesse: ["fazer"],
  fizessem: ["fazer"],
  fazia: ["fazer"],
  faziam: ["fazer"],
  fiz: ["fazer"],
  foi: ["ir", "ser"],
  foram: ["ir", "ser"],
  fora: ["ir", "ser"],
  forem: ["ir", "ser"],
  fosse: ["ir", "ser"],
  fossem: ["ir", "ser"],
  fomos: ["ir", "ser"],
  for: ["ir", "ser"],
  forais: ["ir", "ser"],
  fui: ["ir", "ser"],
  hei: ["haver"],
  ha: ["haver"],
  hao: ["haver"],
  havera: ["haver"],
  haverao: ["haver"],
  haverei: ["haver"],
  haveria: ["haver"],
  haveriam: ["haver"],
  houve: ["haver"],
  houver: ["haver"],
  houvera: ["haver"],
  houveram: ["haver"],
  houverem: ["haver"],
  houvesse: ["haver"],
  houvessem: ["haver"],
  havia: ["haver"],
  haviam: ["haver"],
  ia: ["ir"],
  iam: ["ir"],
  ira: ["ir"],
  irao: ["ir"],
  irei: ["ir"],
  iria: ["ir"],
  iriam: ["ir"],
  posso: ["poder"],
  pode: ["poder"],
  podem: ["poder"],
  podes: ["poder"],
  podera: ["poder"],
  poderao: ["poder"],
  poderei: ["poder"],
  poderia: ["poder"],
  poderiam: ["poder"],
  podia: ["poder"],
  podiam: ["poder"],
  pude: ["poder"],
  puderam: ["poder"],
  puder: ["poder"],
  pudera: ["poder"],
  puderem: ["poder"],
  pudesse: ["poder"],
  pudessem: ["poder"],
  poe: ["p\u00f4r"],
  poem: ["p\u00f4r"],
  ponho: ["p\u00f4r"],
  pora: ["p\u00f4r"],
  porao: ["p\u00f4r"],
  porei: ["p\u00f4r"],
  poria: ["p\u00f4r"],
  poriam: ["p\u00f4r"],
  pus: ["p\u00f4r"],
  puser: ["p\u00f4r"],
  pusera: ["p\u00f4r"],
  puseram: ["p\u00f4r"],
  puserem: ["p\u00f4r"],
  pusesse: ["p\u00f4r"],
  pusessem: ["p\u00f4r"],
  queira: ["querer"],
  queiram: ["querer"],
  queiramos: ["querer"],
  queiras: ["querer"],
  quero: ["querer"],
  quer: ["querer"],
  querem: ["querer"],
  queremos: ["querer"],
  querera: ["querer"],
  quererao: ["querer"],
  quererei: ["querer"],
  quereria: ["querer"],
  quereriam: ["querer"],
  queres: ["querer"],
  queria: ["querer"],
  queriam: ["querer"],
  quisera: ["querer"],
  quiser: ["querer"],
  quiseram: ["querer"],
  quiserem: ["querer"],
  quisesse: ["querer"],
  quisessem: ["querer"],
  quis: ["querer"],
  sabe: ["saber"],
  sabeis: ["saber"],
  sabem: ["saber"],
  sabemos: ["saber"],
  sabes: ["saber"],
  sabera: ["saber"],
  saberao: ["saber"],
  saberei: ["saber"],
  saberia: ["saber"],
  saberiam: ["saber"],
  sabia: ["saber"],
  sabiam: ["saber"],
  soube: ["saber"],
  souber: ["saber"],
  soubera: ["saber"],
  souberam: ["saber"],
  souberem: ["saber"],
  soubesse: ["saber"],
  soubessem: ["saber"],
  sao: ["ser"],
  sera: ["ser"],
  serao: ["ser"],
  serei: ["ser"],
  seria: ["ser"],
  seriam: ["ser"],
  somos: ["ser"],
  sou: ["ser"],
  sois: ["ser"],
  tem: ["ter"],
  tens: ["ter"],
  tendes: ["ter"],
  temos: ["ter"],
  tenha: ["ter"],
  tenham: ["ter"],
  tenhamos: ["ter"],
  tenhas: ["ter"],
  tera: ["ter"],
  terao: ["ter"],
  terei: ["ter"],
  teria: ["ter"],
  teriam: ["ter"],
  tinha: ["ter"],
  tinham: ["ter"],
  tive: ["ter"],
  tiver: ["ter"],
  tivera: ["ter"],
  tiveram: ["ter"],
  tiverem: ["ter"],
  tivesse: ["ter"],
  tivessem: ["ter"],
  trago: ["trazer"],
  traz: ["trazer"],
  trazeis: ["trazer"],
  trazem: ["trazer"],
  trazemos: ["trazer"],
  trazera: ["trazer"],
  trazerao: ["trazer"],
  trarei: ["trazer"],
  traria: ["trazer"],
  trariam: ["trazer"],
  trouxe: ["trazer"],
  trouxer: ["trazer"],
  trouxera: ["trazer"],
  trouxeram: ["trazer"],
  trouxerem: ["trazer"],
  trouxesse: ["trazer"],
  trouxessem: ["trazer"],
  vai: ["ir"],
  vao: ["ir"],
  vais: ["ir"],
  vamos: ["ir"],
  veio: ["vir"],
  veja: ["ver"],
  vejam: ["ver"],
  vejamos: ["ver"],
  vejas: ["ver"],
  vejo: ["ver"],
  ve: ["ver"],
  veem: ["ver"],
  vedes: ["ver"],
  verei: ["ver"],
  vera: ["ver"],
  verao: ["ver"],
  veria: ["ver"],
  veriam: ["ver"],
  vi: ["ver"],
  via: ["ver"],
  viam: ["ver"],
  vira: ["ver", "vir"],
  virao: ["ver", "vir"],
  viria: ["ver", "vir"],
  viriam: ["ver", "vir"],
  vir: ["vir"],
  vier: ["vir"],
  viera: ["vir"],
  vieram: ["vir"],
  vierem: ["vir"],
  viesse: ["vir"],
  viessem: ["vir"],
  viu: ["ver"],
  vimos: ["ver", "vir"],
  vim: ["vir"],
  vinha: ["vir"],
  vinham: ["vir"],
  venho: ["vir"],
  vem: ["vir"],
  vens: ["vir"],
  vindes: ["vir"],
  vou: ["ir"],
};

const LEMMA_RULES: LemmaRule[] = [
  { suffix: "guei", lemmas: (stem) => [`${stem}gar`] },
  { suffix: "quei", lemmas: (stem) => [`${stem}car`] },
  { suffix: "cei", lemmas: (stem) => [`${stem}\u00e7ar`] },
  { suffix: "guem", lemmas: (stem) => [`${stem}gar`] },
  { suffix: "quem", lemmas: (stem) => [`${stem}car`] },
  { suffix: "cem", lemmas: (stem) => [`${stem}\u00e7ar`] },
  { suffix: "gue", lemmas: (stem) => [`${stem}gar`] },
  { suffix: "que", lemmas: (stem) => [`${stem}car`] },
  { suffix: "ce", lemmas: (stem) => [`${stem}\u00e7ar`] },
  { suffix: "ariam", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "arias", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "ariamos", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "arieis", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "areis", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "aremos", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "arao", lemmas: (stem) => [`${stem}ar`], minStemLength: 1 },
  { suffix: "aras", lemmas: (stem) => [`${stem}ar`], minStemLength: 1 },
  { suffix: "ara", lemmas: (stem) => [`${stem}ar`], minStemLength: 1 },
  { suffix: "ariam", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "eriam", lemmas: (stem) => [`${stem}er`], minStemLength: 1 },
  { suffix: "erias", lemmas: (stem) => [`${stem}er`], minStemLength: 1 },
  { suffix: "eriamos", lemmas: (stem) => [`${stem}er`], minStemLength: 1 },
  { suffix: "erieis", lemmas: (stem) => [`${stem}er`], minStemLength: 1 },
  { suffix: "ereis", lemmas: (stem) => [`${stem}er`], minStemLength: 1 },
  { suffix: "eremos", lemmas: (stem) => [`${stem}er`], minStemLength: 1 },
  { suffix: "erao", lemmas: (stem) => [`${stem}er`], minStemLength: 1 },
  { suffix: "eras", lemmas: (stem) => [`${stem}er`], minStemLength: 1 },
  { suffix: "era", lemmas: (stem) => [`${stem}er`], minStemLength: 1 },
  { suffix: "iriam", lemmas: (stem) => [`${stem}ir`], minStemLength: 1 },
  { suffix: "irias", lemmas: (stem) => [`${stem}ir`], minStemLength: 1 },
  { suffix: "iriamos", lemmas: (stem) => [`${stem}ir`], minStemLength: 1 },
  { suffix: "irieis", lemmas: (stem) => [`${stem}ir`], minStemLength: 1 },
  { suffix: "ireis", lemmas: (stem) => [`${stem}ir`], minStemLength: 1 },
  { suffix: "iremos", lemmas: (stem) => [`${stem}ir`], minStemLength: 1 },
  { suffix: "irao", lemmas: (stem) => [`${stem}ir`], minStemLength: 1 },
  { suffix: "iras", lemmas: (stem) => [`${stem}ir`], minStemLength: 1 },
  { suffix: "ira", lemmas: (stem) => [`${stem}ir`], minStemLength: 1 },
  { suffix: "assemos", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "asses", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "armos", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "arem", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "ares", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "essemos", lemmas: (stem) => [`${stem}er`], minStemLength: 1 },
  { suffix: "esses", lemmas: (stem) => [`${stem}er`], minStemLength: 1 },
  { suffix: "ermos", lemmas: (stem) => [`${stem}er`], minStemLength: 1 },
  { suffix: "erem", lemmas: (stem) => [`${stem}er`], minStemLength: 1 },
  { suffix: "eres", lemmas: (stem) => [`${stem}er`], minStemLength: 1 },
  { suffix: "issemos", lemmas: (stem) => [`${stem}ir`], minStemLength: 1 },
  { suffix: "isses", lemmas: (stem) => [`${stem}ir`], minStemLength: 1 },
  { suffix: "irmos", lemmas: (stem) => [`${stem}ir`], minStemLength: 1 },
  { suffix: "irem", lemmas: (stem) => [`${stem}ir`], minStemLength: 1 },
  { suffix: "ires", lemmas: (stem) => [`${stem}ir`], minStemLength: 1 },
  { suffix: "izem", lemmas: (stem) => [`${stem}izar`] },
  { suffix: "ize", lemmas: (stem) => [`${stem}izar`] },
  { suffix: "izo", lemmas: (stem) => [`${stem}izar`] },
  { suffix: "izam", lemmas: (stem) => [`${stem}izar`] },
  { suffix: "izas", lemmas: (stem) => [`${stem}izar`] },
  { suffix: "izou", lemmas: (stem) => [`${stem}izar`] },
  { suffix: "izava", lemmas: (stem) => [`${stem}izar`] },
  { suffix: "izavam", lemmas: (stem) => [`${stem}izar`] },
  { suffix: "izaria", lemmas: (stem) => [`${stem}izar`] },
  { suffix: "izariam", lemmas: (stem) => [`${stem}izar`] },
  { suffix: "izara", lemmas: (stem) => [`${stem}izar`] },
  { suffix: "izarao", lemmas: (stem) => [`${stem}izar`] },
  { suffix: "ei", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "aste", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "ou", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "amos", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "aram", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "ava", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "avam", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "ando", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "ado", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "ada", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "ados", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "adas", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "em", lemmas: (stem) => [`${stem}ar`], minStemLength: 4 },
  { suffix: "es", lemmas: (stem) => [`${stem}ar`], minStemLength: 4 },
  { suffix: "e", lemmas: (stem) => [`${stem}ar`], minStemLength: 4 },
  { suffix: "arei", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "aria", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "asse", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "assem", lemmas: (stem) => [`${stem}ar`] },
  { suffix: "este", lemmas: (stem) => [`${stem}er`] },
  { suffix: "eu", lemmas: (stem) => [`${stem}er`] },
  { suffix: "emos", lemmas: (stem) => [`${stem}er`] },
  { suffix: "eram", lemmas: (stem) => [`${stem}er`] },
  { suffix: "endo", lemmas: (stem) => [`${stem}er`] },
  { suffix: "erei", lemmas: (stem) => [`${stem}er`] },
  { suffix: "eria", lemmas: (stem) => [`${stem}er`] },
  { suffix: "esse", lemmas: (stem) => [`${stem}er`] },
  { suffix: "essem", lemmas: (stem) => [`${stem}er`] },
  { suffix: "iste", lemmas: (stem) => [`${stem}ir`] },
  { suffix: "iu", lemmas: (stem) => [`${stem}ir`] },
  { suffix: "imos", lemmas: (stem) => [`${stem}ir`] },
  { suffix: "iram", lemmas: (stem) => [`${stem}ir`] },
  { suffix: "indo", lemmas: (stem) => [`${stem}ir`] },
  { suffix: "irei", lemmas: (stem) => [`${stem}ir`] },
  { suffix: "iria", lemmas: (stem) => [`${stem}ir`] },
  { suffix: "isse", lemmas: (stem) => [`${stem}ir`] },
  { suffix: "issem", lemmas: (stem) => [`${stem}ir`] },
  { suffix: "am", lemmas: (stem) => [`${stem}er`, `${stem}ir`], minStemLength: 4 },
  { suffix: "as", lemmas: (stem) => [`${stem}er`, `${stem}ir`], minStemLength: 4 },
  { suffix: "a", lemmas: (stem) => [`${stem}er`, `${stem}ir`], minStemLength: 4 },
  { suffix: "ia", lemmas: (stem) => [`${stem}er`, `${stem}ir`] },
  { suffix: "iam", lemmas: (stem) => [`${stem}er`, `${stem}ir`] },
  { suffix: "ido", lemmas: (stem) => [`${stem}er`, `${stem}ir`] },
  { suffix: "ida", lemmas: (stem) => [`${stem}er`, `${stem}ir`] },
  { suffix: "idos", lemmas: (stem) => [`${stem}er`, `${stem}ir`] },
  { suffix: "idas", lemmas: (stem) => [`${stem}er`, `${stem}ir`] },
  {
    suffix: "o",
    lemmas: (stem) => [`${stem}ar`, `${stem}er`, `${stem}ir`],
    minStemLength: 4,
  },
  { suffix: "i", lemmas: (stem) => [`${stem}er`, `${stem}ir`] },
];

function normalizeVerbKey(value: string) {
  return normalizeInlineText(value)
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .toLocaleLowerCase("pt-BR");
}

function isLikelyInfinitive(value: string) {
  return value === "p\u00f4r" || /(ar|er|ir)$/i.test(value);
}

function isValidLemma(value: string) {
  return value.length >= 2 && /^[\p{L}\p{M}]+$/u.test(value) && isLikelyInfinitive(value);
}

function uniqueLemmas(values: string[]) {
  const seen = new Set<string>();
  const unique: string[] = [];

  for (const value of values) {
    const normalized = normalizeVerbKey(value);

    if (seen.has(normalized)) {
      continue;
    }

    seen.add(normalized);
    unique.push(value);
  }

  return unique;
}

export function inferPortugueseVerbLemmas(word: string) {
  const rawWord = normalizeInlineText(word.normalize("NFC")).toLocaleLowerCase("pt-BR");
  const normalizedWord = normalizeVerbKey(word);

  if (!normalizedWord || isLikelyInfinitive(normalizedWord)) {
    return [];
  }

  const candidates = [...(IRREGULAR_FORMS[normalizedWord] ?? [])];

  for (const rule of LEMMA_RULES) {
    if (!normalizedWord.endsWith(rule.suffix)) {
      continue;
    }

    const stem = normalizedWord.slice(0, -rule.suffix.length);
    const rawStem = rawWord.slice(0, -rule.suffix.length);

    if (stem.length < (rule.minStemLength ?? 2)) {
      continue;
    }

    candidates.push(...rule.lemmas(rawStem || stem));
  }

  return uniqueLemmas(candidates.filter(isValidLemma));
}
